### ISSUE TITLE
Research Content Delivery

### ISSUE THREAD

**Issue by Cotrina9** [gmo/grant#10]
Research what would be the most efficient and effective way to delivery up content to the potential of thousands of churches as part of the Google Grant Initiative.

**Comment by mikegillis677** [comment]
Probably want to start with whatever CV was doing.  I have a copy of their javascript.

[cvgospel.min.js.zip](https://github.com/gmo/grant/files/1656707/cvgospel.min.js.zip)

**Comment by mikegillis677** [comment]
Tentative, temporary solution until we get something better:
```
<div id="gmo-page-container"></div>
<script src="//glcdn.co/grant/js/gospel_0.js"></script>
```

**Comment by mikegillis677** [comment]
Two of the final gospel presentations were available to be converted to an embeddable version.  Unfortunately, the way they were built into the site meant that I couldn't just scrape the site for the content because the CSS would be off since the final CSS was a mix of the CSS from the rest of the site and the CSS unique to the gospel presentation.

**Comment by mikegillis677** [comment]
Here's the embed codes for the other gospel presentations.
4Steps:
```
<div id="gmo-page-container"></div>
<script src="//glcdn.co/grant/js/gospel_1.js"></script>
```

Here's the embed code for the Abundant Life presentation:
```
<div id="gmo-page-container"></div>
<script src="//glcdn.co/grant/js/gospel_0.js"></script>
```
