### ISSUE TITLE
Test AMP pages

### ISSUE THREAD

**Issue by Cotrina9** [gmo/grant#14]
Per Katherine - Test AMP pages on one/two of our gospel presentations - https://www.ampproject.org/

**Comment by mikegillis677** [comment]
I managed to get an AMP gospel presentation built and validating in branch `feature/faith-amp`.  However, when I was going over the AMP Cache, I discovered that the AMP Cache that Google operates would break our tracking.  The reason being that we would be unable to generate a visitorId (since javascript is blocked), and we would be unable to do device detection & geolocation (since the stats tracking hit for AMP Analytics would come from Google's servers).

**Comment by mikegillis677** [comment]
It might be possible to do our own analytics with GeoLocation by using the amp-list and amp-mustache components together like in this example:
https://ampbyexample.com/advanced/geolocation_with_amp-list/

In our case, the amp-list component would call a new API on our server that would do the geolocation and pass it back.  Then amp-mustache would output a tracking pixel.  I'm not sure how to integrate visitorId with this, though (maybe generate the entire decision block with mustache and embed the new visitorId in the yes & no links?)

**Comment by Cotrina9** [comment]
There is an issue with being able to track this and would require complete redo of how we do tracking currently.
