### ISSUE TITLE
Google Grant Click Loss

### ISSUE THREAD

**Issue by Cotrina9** [gmo/grant#34]
Per Sarah - I've noticed there seems to be a significant amount of click loss on some of the grant accounts. I analyzed all the accounts and found 3 that seem to be having some sort of tracking issue. The Chapel looks like it's double counting the people coming to their site. Igniting Prayer Action and International Service Corps of Asia are having a problem where they seem to be loosing around half the clicks (AdWords to Tableau). I've attached a document showing the click loss data from May. 

[Click Loss (1).docx](https://github.com/gmo/grant/files/2039734/Click.Loss.1.docx)

**Comment by Cotrina9** [comment]
As requested the URL's are below - 

[URLS.docx](https://github.com/gmo/grant/files/2073953/URLS.docx)

**Comment by mikegillis677** [comment]
The cause of the double counting on The Chapel's website is that someone put the gospel embed code on the page twice.  That'll cause the stats tracking to fire twice.

**Comment by mikegillis677** [comment]
The problem with the Google Adwords conversion code on Igniting Prayer Action (it's not firing) is because someone copied the conversion tracking code wrong.  The quotes being used are slanted quotes instead of normal quotes, so it's not being interpreted as a conversion tracking code by the web browsers.

I am presuming that International Service Corps of Asia is having the same problem, but I can't verify that right now because the site is down.

**Comment by Cotrina9** [comment]
Per Jackie - • Jackie submitted this request on 6/8/18 and we are adding it to this ZenHub ticket - Per Jackie - The Chapel had duplicate code on their webpage and therefore, all Google tracking was counting GV, ID and NC twice.  Their webpage, http://thechapel-efc.org/the-gospel, has been fixed.  The start date on this site was 3/21/2018.  Can you fix the counts to eliminate the duplications from the beginning since we are reporting to them monthly and FY totals each month?  I'm not sure of the complexity of this request, but am requesting that it get done as soon as possible so that we can generate a corrected report for them by June 15, when we send out GO Grant reports.  Thank you.

**Comment by mikegillis677** [comment]
Regarding Jackie's request:
I can make changes to our official stats for April 2018 and May 2018, but I can’t make the same changes to the operational data.  The reason being that by doing so, I would have to choose 50% of the individual line item data to remove, and by doing so I would probably corrupt the city/state/country/ad, etc. breakdowns since I can’t think of a way to isolate just the line item duplicates from the operational data.

**Comment by Cotrina9** [comment]
Per Jackie - Please make the changes to the official stats for April and May and verify that the data is not being duplicated currently.

**Comment by mikegillis677** [comment]
I've changed the official stats for April and May.  I've also verified that the stats aren't currently being duplicated.
